CREATE TABLE resume_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL,
    title VARCHAR(150) NOT NULL,
    content TEXT,
    file_path VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_resume_version_number UNIQUE (resume_id, version_number),
    CONSTRAINT fk_resume_versions_resume FOREIGN KEY (resume_id) REFERENCES resumes(id)
);

CREATE INDEX idx_resume_versions_resume_id ON resume_versions(resume_id);
