CREATE TABLE github_connections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    github_user_id BIGINT,
    github_username VARCHAR(255) NOT NULL,
    github_name VARCHAR(255),
    avatar_url VARCHAR(500),
    bio TEXT,
    html_url VARCHAR(500),
    access_token VARCHAR(500) NOT NULL,
    followers INTEGER DEFAULT 0,
    following INTEGER DEFAULT 0,
    public_repos INTEGER DEFAULT 0,
    connected_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_github_connections_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_github_connections_user_id ON github_connections(user_id);
